name: snow_to_smax
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mongo_dart: ^0.4.0
  logger: ^0.9.4
  universal_html: ^1.2.4
  
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
